DROP TRIGGER IF EXISTS Indseattelse

GO

CREATE TRIGGER Indsaettelse
ON AlleKunder
INSTEAD OF INSERT AS
BEGIN
	IF (SELECT kundeid FROM INSERTED) % 2 = 0
		INSERT INTO destA.dbo.Kunder SELECT * FROM INSERTED
	ELSE
 		INSERT INTO destB.dbo.Kunder SELECT * FROM INSERTED
END